# The URL the site will be built for
base_url = "https://hyde--gutenberg-theme-demo.netlify.com"

# Whether to automatically compile all Sass files in the sass directory

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Gutenberg
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "hyde"

title = "Hyde Demo"

description = "A demonstration of the Hyde theme for Gutenberg"
[extra]
# Put all your custom variables here
hyde_links = [
  { url = "https://github.com/Keats/hyde", name = "Theme Source" },
  { url = "https://www.github.com/codesections/gutenberg-theme-demo/tree/hyde", name = "Site Source" },
  { url = "https://www.getgutenberg.io/themes/", name = "Additional Themes" },
]
